global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
- job_name: 'rails'
  scheme: http
  metrics_path: '/metrics'
  static_configs:
    - targets:
      - 'host.docker.internal:3000'
